version: '3.7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sistema-votacao
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=sistema-db
    volumes:
      - sistema_votacao_pg_data:/bitnami/postgresql

volumes:
  sistema_votacao_pg_data:
